Homework2: Denis Borisenko
belovmd/it-academy-winter-2020 pull request #40
Opened 2020-12-05 15:38 UTC by dambo-dambo

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle)
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks
- [ ] my PR made from the fork feature branch to maxim homework# branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore

2020-12-09 23:31 UTC, belovmd requested changes
you can add 2 additional advanced tasks for higher score

2020-12-09 23:31 UTC, belovmd commented on src/homework2/task2.py
> +string = input('Введите предложение: ')
don't solve task in description

2020-12-09 23:31 UTC, belovmd commented on src/homework2/task5.py
> +number1 = 0
1, 1 - start values

2020-12-19 16:14 UTC, dambo-dambo commented
hw

2020-12-19 17:17 UTC, dambo-dambo reviewed
w

2020-12-25 19:00 UTC, belovmd reviewed
8,5

2020-12-25 19:00 UTC, belovmd commented on src/homework2/task7.py
> +   который возвращает строку этих чисел в форме номера телефона.
easy task for python

2020-12-25 19:00 UTC, closed without merging