Homework3:Anton Gorulev
belovmd/it-academy-winter-2020 pull request #69
Opened 2020-12-26 16:20 UTC by AntonGorulev

### PR checklist
Please make sure you've passed PR checklist
- [ ] my PR passes CI checks (flake8 and pycodestyle)
- [ ] my PR named according to guidelines.
- [ ] my PR contains complete tasks descriptions for all tasks
- [ ] my PR made from the fork feature branch to maxim homework# branch.
- [ ] my PR contains only code that solves appropriate homework tasks. Redundant 
files (configs, etc. ) are put to .gitignore

2021-01-08 02:15 UTC, belovmd requested changes
sanity checks failed: redundant files in code (hw1, hw2)

please address next issues

2021-01-08 02:15 UTC, belovmd commented on src/Homework2./task1.py
> +'''
bad folder name. should be snake_case without special symbols

2021-01-08 02:15 UTC, belovmd commented on src/Homework3./task1.py
> +'''
bad file name

2021-01-08 02:15 UTC, belovmd commented on src/Homework3./task1.py
> +    if x % 3 == 0 and x % 5 == 0:
15?

2021-01-08 02:15 UTC, belovmd commented on src/Homework3./task2.py
> +list_1 = [str(_) + 'a' for _ in range(1, 5)]
'1234'?

2021-01-08 02:15 UTC, belovmd commented on src/Homework3./task3.py
> +tuple_1 = ('1, 2, 3', )
doesn't solve task in description

2021-01-08 02:15 UTC, belovmd commented on src/Homework3./task3.py
> +    print(_)
bad naming. _ - for unused vars

2021-01-08 02:15 UTC, belovmd commented on src/Homework3./task5.py
> +    if list_.count(_) == 1:
O(n**2) solution. can be solved with O(n)

2021-01-08 02:15 UTC, belovmd commented on src/Homework3./task5.py
> +for _ in list_:
bad naming

2021-01-08 02:15 UTC, belovmd commented on src/Homework3./task6.py
> +for _ in list_:
bad naming

2021-04-10 15:43 UTC, closed without merging

2021-04-10 15:43 UTC, AntonGorulev commented
Add new PR for Homework3